
solution:
    benefits:
      - remote:
        name: 
            en: Discover Assets
        description: 
            en: Badrap discovers your digital footprint always automatically 
        cta: 
            en: Try badrap.io
        icon: ti-cloud
        producturl: https://badrap.io/
        target: target="_blank"
        id: gt-badrap-personal

      - discover:
        name: 
            en: Get relevant security content
        description: 
            en: Badrap steers you to relevant security information.
        cta: 
            en: Read more
        icon: ti-cloud
        producturl: /employees/
        id: gt-badrap-companies
        largeicon:
            src:
                en: it/cloud-banner.svg
            alt:
                en: People operating cloud
      - fixes:
        name: 
            en: Fixes issues
        description:   
            en: Alerts alone are a distraction. Badrap helps you with fixes.
        tagline: 
            en: Cover your company assets. 
        cta: 
            en: Read more
        icon: ti-book
        producturl: /it/
        id: gt-badrap-product

    features:
        content:
            headline:
                en: Keep track of your cloud, no fuss.
            description:
                en: "Always up to date information what you have in cloud. Discover your email addresses, IPs and domain names on three leading cloud platforms: Microsoft, Amazon and Google."
        apps:
            headline:
                en: Badrap Apps
            description:
                en: >
                     Integrate your own security providers and share up-to-date asset infromation to them, or receive their alerts.
            list:
              - aws:
                name:
                    en: Amazon Web Services
                description:
                    en: Synchronize your public IPs and domains from Amazon Web Services to Badrap
                icon:
                    src: img/aws.svg
              - azure:
                name: 
                    en: Microsoft Azure
                icon:
                    src: img/azure.svg
                description:
                    en: Synchronize your public IPs and domains from Microsoft Azure to Badrap
              - o365:
                name:
                    en: Microsoft Office 365
                icon:
                    src: img/office365.svg
                description:
                    en: Syncrhonize email addresses from O365 to Badrap
              - gcp:
                name:
                    en: Google Cloud Platform
                description:
                    en: Synchronize your public IPs and domains from Google Cloud Platform to Badrap
                icon:
                    src: img/gcp.png
              - gsuite:
                name: 
                    en: Google G Suite
                description:
                    en: Syncrhonize email addresses from Google G Suite to Badrap
                icon:
                    src: img/gsuite.png
              - beacon:
                name: 
                    en: SensorFu Beacon
                description:
                    en: Get leak alerts from SensorFu Beacon to Badrap
                icon:
                    src: img/beacon.svg

              - traficom:
                name:
                    en: Traficom
                description:
                    en: Share assets with Traficom's National Cyber Security Center
                icon:
                    src: img/traficom.svg


playbooks:
    heading:
        en: Fix issues with Badrap playbooks
    subheading:
        en: We learn from the best - our customers - about the best ways to fix issues. We add that knowledge to our product, along with easy access to the right fixers.
    list:
      - hygiene:
        id: "tab3_sec1"
        status: active
        show: show
        name:
            en: Employee Cyber Hygiene
        subheading: 
            en: Mitigate data leaks.
        description:
            en: Data leaks fuel phishing and scams. Protect your business by protecting your employees.
        steps:
            - Subscribe to data leak content
            - Enable O365 or G Suite integration
            - Receive alerts about data leak victims in your organisation and launch vitcim training.
        img:
            src: /img/study.svg
            alt: Learning
      - supplychain:
        id: "tab3_sec2"
        name:
            en: Supply Chain Caretaking
        heading:
            en: Address 3rd party security lapses
        description:
            en: Check third party security issues and get them fixed
        steps:
            - Subscribe to vulnerability and incident content
            - Enable cloud asset discovery Apps to identify your cloud assets
            - Receive alerts about security lapses in your cloud infra and ticket your contractors to demand fixes
        img:
            src: /img/cloud.svg
            alt: Learning